version: '3'

services:
  fab:
    build: 
      context: ./3Dgallery
    ports:
      - 8080:8080
    depends_on:
      - db
  node:
    build:
      context: ./node/
    ports:
      - 3000:3000
    depends_on:
      - fab
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: app
      POSTGRES_PASSWORD: pguserpassword
      POSTGRES_USER: pguser
    ports:
      - 5432:5432