version: '3'

services:
  fab-backend:
    build: 
      context: ./
    ports:
      - "5000:5000"
    depends_on:
      - postgres
  postgres:
    image: postgres:13.5-alpine
    expose:
      - "5432"
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "user"
      POSTGRES_DB: "app"
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
volumes:
  db-data: